mode_mappings:
  B: # PauseWaypoints
    "*":
      action_type: system
      cmd: pause_waypoints

  A: # ResumeWaypoints
    "*":
      action_type: system
      cmd: resume_waypoints

  Start:
    "*":
      action_type: system
      cmd: stop_waypoints

  X: # SwitchRef1
    "*":
      action_type: mode
      mode_cmd: toggle_next
  Back: 
    "*": 
      action_type: waypoint_demo
      reference_frame: j2n6s300_link_base
      waypoints:
          - { x: 0.5,  y: 0.0,  z: 0.47, roll: -200, pitch: 85, yaw: 170, time: 5.0 }
