/glasses_emulator_node:
  ros__parameters:
    camera_id: 0
    publish_freq: 50
    draw_circle: false
    camera_depth: 1.0
    video_resolution:
      - 1600
      - 1200
    print_performance: False
    camera_matrix:
      [
        883.10398037,
        0.0,
        796.76508223,
        0.0,
        889.42718313,
        646.25149238,
        0.0,
        0.0,
        1.0,
      ]
    dist_coeff: [-0.28984511, 0.08497217, -0.00134947, -0.00125141, -0.01016795]

/pupil_glasses_node:
  ros__parameters:
    publish_freq: 50
    draw_circle: true
    camera_depth: 1.0
    video_resolution:
      - 1600
      - 1200
    ip: "10.0.0.2"
    port: "8080"
    print_performance: False
  
/aruco_detector:
  ros__parameters:
        aruco_dict : "DICT_4X4_250"
        marker_size : 0.0437
        camera_frame : "camera_optical_frame" 
        publish_tf : True
        publish_poses : False
        marker_persistence : 0.9
        filter_min_cutoff : 0.5 
        filter_beta : 0.00005  

/button_finder:
  ros__parameters:
        button_center_strategy : "inverse_square"
        button_map_path : "src/diegetic_transform_engine/button_maps/ButtonMap - O-Joy V3.csv"
        # camera_frame_id : "camera_optical_frame"
        # button_frame_id : "button_frame"

/command_mapper_node:
  ros__parameters:
    axis_threshold: 0.6
    parser_mappings_file: "EMANUEL_mode_config.inputs.yaml"

/dwell_time:
  ros__parameters:
    interaction_mode: "dwell_time" #  "immediate"  # Activate immediately on hover
    dwell_duration_seconds: 0.7
    activation_threshold : 0.2
    hover_threshold : 0.1
    deactivation_threshold : 0.2
    processing_mode: 'gaze_driven'
    processing_frequency : 30 
    button_timeout_seconds: 0.9
    publish_debug_image: False
    verbose_logging: False


/gaze_controller_node:
  ros__parameters:
    compensation_active : False 
    use_temporal_alignment : True
    sticky_button_interaction : False
    history_length_s : 5.0
    internal_pipeline_delay_ms : 0.0
    median_window : 20
    ema_alpha : 0.2
    edge_margin : 50
    start_trim_ms : 50.0   # Start Padding 
    terminal_trim_ms : 100.0  # End padding 
    min_event_duration_ms : 200.0 #  
    max_compensation_px : 200.0
    viz_enabled : True


/calibration_learner_node:
  ros__parameters:
    show_binned_truth: True
    show_prediction : True
    show_raw_samples : True
    publish_debug_image : True
    publish_prediction_map: True