/diegetic_button_pubsub_node:
  ros__parameters:
    #button_map_path: "src/diegetic_button_pkg/button_maps/ButtonMap - O-Joy V2.1.csv"
    button_map_path: "src/diegetic_button_pkg/button_maps/ScreenMap.csv"
    #button_map_path: "src/diegetic_button_pkg/button_maps/ButtonMap - A3Piano.csv"
    #button_map_path: "src/diegetic_button_pkg/button_maps/ButtonMap-Ink(boo).csv"
    button_center_finding_mode: "inverse_quintic"

/process_inputs_node:
  ros__parameters: 
    input_trigger_mode: "dwell_time"
    cycle_duration_seconds: 0.400  # seconds to complete transition
    active_threshold_percent: 0.60  # percentage. Close to 0 start quickly
    inactive_threshold_percent: 0.400  # percentage. Close to 1 stop quickly
    publish_image : True
    draw_on_fiducials : True
    serial_com : False
    send_serial : False

/process_inputs_node:
  ros__parameters:
    camera_matrix:
      [
            887.79147665,
            0.0,
            809.32877594,
            0.0,
            887.14056667,
            614.39688332,
            0.0,
            0.0,
            1.0,
      ]
    dist_coeff:
      [
            -1.28152845e-01,
            1.06973881e-01,
            -1.50877076e-05,
            -9.10823342e-04,
            2.62431778e-03,
            1.69108143e-01,
            5.02584562e-02,
            2.94127262e-02,
      ]
