<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gaze_screen_interface</name>
  <version>0.1.0</version>
  <description>Gaze-controlled screen interface with ROS2 integration</description>
  <maintainer email="enuenzsardinha@gmail.com">root</maintainer>
  <license>MIT</license>

 <!-- CMake build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <!-- ROS2 dependencies -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  
  <!-- Your custom message packages -->
  <depend>diegetic_transform_engine</depend>
  <depend>gaze_interaction_manager</depend>

  <!-- Testing -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>python3-pytest</test_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
