"""threading code taken from: https://www.codepile.net/pile/ey9KAnxn

found something about this being a complex way to implement threading here:
https://mayaposch.wordpress.com/2011/11/01/how-to-really-truly-use-qthreads-the-full-explanation/

but the code uses C++, so I'll have to figure it out later."""


# Start importing PyQt Modules 
# TODO: replace * with actual used functions to declutter namespace.
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QKeySequence

# Import components.
from WebcamStream import ImageThread, VideoStreamWindow
from components import ContinousButton, ClickableLabel, ControlView
from load_controller_publisher import create_controller

# Import external dependencies.
import sys
import cv2
from itertools import cycle
from typing import Collection
import numpy as np
from functools import partial

#TODO: Add this to WebcamStream file.
def find_cameras():
    """Finds all connected webcams and returns a list of their indexes

    Returns: indexes of all connected webcams"""
    # Generated by Claude 3.7
    index = 0
    cameras = []
    while True:
        cap = cv2.VideoCapture(index)
        if not cap.isOpened():
            break
        cameras.append(index)
        cap.release()
        index += 1
    return cameras


class LowerButtonSegment(QWidget):
    def __init__(self, pages):
        super().__init__()

        self.layout = QVBoxLayout()

        # Add control View Button.
        self.change_control_button = QPushButton("Toggle Control Mode")
        self.change_control_button.clicked.connect(self.change_view)
        self.layout.addWidget(self.change_control_button)

        # Add control pane
        self.control_pane = ControlView(pages)
        self.layout.addWidget(self.control_pane)

        self.setLayout(self.layout)


    def change_view(self):
        self.control_pane.setCurrentIndex(next(self.control_pane.widget_list))


class MainWindow(QWidget):
    """The main window of the application, includes the camera feed and control buttons"""

    def __init__(self, controller_publisher, threads, ros_node=None):
        super(MainWindow, self).__init__()
        self.VBL = QVBoxLayout()

        # Set up a publisher to enable ROS messages to be sent from the GUI.
        self.publisher = controller_publisher

        # Initialize camera thread
        if isinstance(threads, Collection):
            for thread in threads:
                thread.start()
        else:
            threads.start()

        # Create the VideoStreamWindow with all camera threads.
        self.video_stream_window = VideoStreamWindow(
            self.publisher.window_translation_callback,
            self.publisher.window_rotation_callback,
            threads,
        )

        self.VBL.addWidget(self.video_stream_window)

        # Set up rotation and translate page functionality.
        pages = {
            "translation": {
                "↑": partial(
                    self.publisher.button_translation_callback, "forward"
                    ),
                "↓": partial(
                    self.publisher.button_translation_callback, "backward"
                    ),
            },
            "rotation": {
                "↻": partial(
                    self.publisher.button_rotation_callback, "clockwise"
                    ),
                "↺": partial(
                    self.publisher.button_rotation_callback, "anticlockwise"
                ),
            },
        }

        # Create the control pane
        self.lower_button_segment = LowerButtonSegment(pages)
        self.VBL.addWidget(self.lower_button_segment)

        # bind camera change and input mode change buttons to key presses.
        input_mode_key_seq = QKeySequence(Qt.Key_Space)
        camera_mode_key_seq = QKeySequence(Qt.Key_Tab)

        # Bind rotation and fowards and backwards buttons to keypreses.

        # Create lower button segment.
        input_mode_button = self.lower_button_segment.change_control_button
        self.lower_button_segment.control_pane.currentChanged.connect(
            self.update_image_click_func
        )

        self.keybind_btn_click(input_mode_key_seq, input_mode_button)
        # self.keybind_btn_click(camera_mode_key_seq, self.video_stream_window)

        # Create button to switch between camera views.
        self.camera_switch_button = QPushButton("Switch Camera")
        self.camera_switch_button.clicked.connect(
            self.video_stream_window.switch_camera
        )

        self.keybind_btn_click(camera_mode_key_seq, self.camera_switch_button)
        self.VBL.addWidget(self.camera_switch_button)

        self.change_frame_button = QPushButton("Change movment mode")
        self.VBL.addWidget(self.change_frame_button)
        

        self.gripper_open_callback = partial(self.publisher.gripper_callback, "open")
        self.gripper_close_callback = partial(self.publisher.gripper_callback, "close")

        self.gripper_open_button = ContinousButton("Open", self.gripper_open_callback)
        self.gripper_close_button = ContinousButton("Close", self.gripper_close_callback)
        
        self.gripper_view = QHBoxLayout()

        self.gripper_title = QLabel("Gripper")
        
        self.gripper_view.addWidget(self.gripper_open_button)
        self.gripper_view.addWidget(self.gripper_close_button)

        self.VBL.addWidget(self.gripper_title)
        self.VBL.addLayout(self.gripper_view)
        
        
        self.setLayout(self.VBL)

        # Create timer function to send message to robot.
        self.timer = QTimer()
        self.timer.timeout.connect(self.publisher.send_message)
        self.timer.start(20)

    def keybind_btn_click(self, key_sequence: QKeySequence, button: QPushButton):
        input_mode_shortcut = QShortcut(key_sequence, self)
        input_mode_shortcut.activated.connect(button.click)

    def update_image_click_func(self, index):
        """Delegate click function update to the VideoStreamWindow"""
        self.video_stream_window.update_image_click_func(index)

    def CancelFeed(self):
        """Stop all camera feeds"""
        self.video_stream_window.cancel_feed()


if __name__ == "__main__":
    #This will only run the main window, ROS will not send commands. use main.py for actual testing.
    np.printoptions(precision=3)
    cameras = [1]
    print(cameras)
    camera_threads = [ImageThread(camera) for camera in cameras]
    print(camera_threads)

    controller_node = create_controller()
    App = QApplication(sys.argv)
    Root = MainWindow(controller_node, camera_threads)
    Root.show()
    sys.exit(App.exec())