from GUI import *
import sys
import rclpy
from GUI import *
import sys
import rclpy
from grab_webcams import get_cam_feeds

class ROSSpinThread(QThread):
    #Generated by claude to stop PyQT blocking rclpy, should probably rewrite interface in Rqt at some point but written in PyQT to enable cross testing.
    def __init__(self, node):
        super().__init__()
        self.node = node
        self.running = True

    def run(self):
        try:
            while self.running and rclpy.ok():
                rclpy.spin_once(self.node, timeout_sec=0.1)
        except Exception as e:
            print(f"ROS spin thread error: {e}")

    def stop(self):
        self.running = False

def main():
    print("starting QApplication")
    app = QApplication(sys.argv)

    print("starting rclpy")
    rclpy.init()
    
    print("finding cameras")
    cameras = get_cam_feeds("C270 HD WEBCAM")
    print(f"{len(cameras)} cameras found")
    
    print("creating threads")
    camera_threads = [ImageThread(camera) for camera in cameras]
    print("threads created")
    
    print("Creating ROS controller")
    controller = create_controller()

    print("starting application")
    root = MainWindow(controller, camera_threads)
    root.show()

    # Create a separate thread for ROS spinning
    ros_spin_thread = ROSSpinThread(controller)
    ros_spin_thread.start()

    try:
        # Run the Qt event loop
        app_exit_code = app.exec_()
        
        # Clean up
        ros_spin_thread.stop()
        ros_spin_thread.wait()
        controller.destroy_node()
        rclpy.shutdown()
        
        sys.exit(app_exit_code)

    except KeyboardInterrupt:
        ros_spin_thread.stop()
        ros_spin_thread.wait()
        controller.destroy_node()
        rclpy.shutdown()

if __name__ == "__main__":
    main()
