#!/usr/bin/env python3
#entirely generated by Claude 4.0 Sonnet

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2


class WebcamPublisher(Node):
    def __init__(self):
        super().__init__('webcam_publisher')
        
        # Create publisher
        self.publisher_ = self.create_publisher(Image, 'camera/image_raw', 10)
        
        # Create timer to publish at 30 FPS
        timer_period = 1.0 / 30.0  # 30 FPS
        self.timer = self.create_timer(timer_period, self.timer_callback)
        
        # Initialize OpenCV bridge and camera
        self.bridge = CvBridge()
        self.cap = cv2.VideoCapture(0)  # Use default camera (usually /dev/video0)
        
        # Set camera properties (optional)
        self.cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
        self.cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
        self.cap.set(cv2.CAP_PROP_FPS, 30)
        
        if not self.cap.isOpened():
            self.get_logger().error('Failed to open camera')
            return
            
        self.get_logger().info('Webcam publisher started')

    def timer_callback(self):
        ret, frame = self.cap.read()
        if ret:
            # Convert OpenCV image to ROS Image message
            msg = self.bridge.cv2_to_imgmsg(frame, 'bgr8')
            msg.header.stamp = self.get_clock().now().to_msg()
            msg.header.frame_id = 'camera_frame'
            
            # Publish the image
            self.publisher_.publish(msg)
        else:
            self.get_logger().warn('Failed to capture image')

    def destroy_node(self):
        # Clean up camera
        if hasattr(self, 'cap'):
            self.cap.release()
        super().destroy_node()


def main(args=None):
    rclpy.init(args=args)
    
    webcam_publisher = WebcamPublisher()
    
    try:
        rclpy.spin(webcam_publisher)
    except KeyboardInterrupt:
        pass
    finally:
        webcam_publisher.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()